// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `com.example.device_volume.DeviceVolumeHelper`
///
/// Thin wrapper around AudioManager for JNIgen.
///
/// Exposes only the subset of AudioManager that the Dart
/// {@code device_volume} plugin needs.
///
extension type DeviceVolumeHelper._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/example/device_volume/DeviceVolumeHelper',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DeviceVolumeHelper> type =
      $DeviceVolumeHelper$Type$();

  /// from: `static public final int STREAM_MUSIC`
  static const STREAM_MUSIC = 3;

  /// from: `static public final int STREAM_RING`
  static const STREAM_RING = 2;

  /// from: `static public final int STREAM_ALARM`
  static const STREAM_ALARM = 4;

  /// from: `static public final int STREAM_NOTIFICATION`
  static const STREAM_NOTIFICATION = 5;

  /// from: `static public final int STREAM_VOICE_CALL`
  static const STREAM_VOICE_CALL = 0;

  /// from: `static public final int STREAM_SYSTEM`
  static const STREAM_SYSTEM = 1;

  /// from: `static public final int FLAG_SHOW_UI`
  static const FLAG_SHOW_UI = 1;

  /// from: `static public final int ADJUST_RAISE`
  static const ADJUST_RAISE = 1;

  /// from: `static public final int ADJUST_LOWER`
  static const ADJUST_LOWER = -1;
  static final _id_new$ = _class.constructorId(r'(Landroid/content/Context;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory DeviceVolumeHelper(jni$_.JObject? context) {
    final _$context = context?.reference ?? jni$_.jNullReference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$context.pointer,
    ).object<DeviceVolumeHelper>();
  }
}

extension DeviceVolumeHelper$$Methods on DeviceVolumeHelper {
  static final _id_getStreamVolume = DeviceVolumeHelper._class.instanceMethodId(
    r'getStreamVolume',
    r'(I)I',
  );

  static final _getStreamVolume =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public int getStreamVolume(int streamType)`
  core$_.int getStreamVolume(core$_.int streamType) {
    return _getStreamVolume(
      reference.pointer,
      _id_getStreamVolume.pointer,
      streamType,
    ).integer;
  }

  static final _id_getStreamMaxVolume = DeviceVolumeHelper._class
      .instanceMethodId(r'getStreamMaxVolume', r'(I)I');

  static final _getStreamMaxVolume =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public int getStreamMaxVolume(int streamType)`
  core$_.int getStreamMaxVolume(core$_.int streamType) {
    return _getStreamMaxVolume(
      reference.pointer,
      _id_getStreamMaxVolume.pointer,
      streamType,
    ).integer;
  }

  static final _id_getStreamMinVolume = DeviceVolumeHelper._class
      .instanceMethodId(r'getStreamMinVolume', r'(I)I');

  static final _getStreamMinVolume =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public int getStreamMinVolume(int streamType)`
  core$_.int getStreamMinVolume(core$_.int streamType) {
    return _getStreamMinVolume(
      reference.pointer,
      _id_getStreamMinVolume.pointer,
      streamType,
    ).integer;
  }

  static final _id_isStreamMute = DeviceVolumeHelper._class.instanceMethodId(
    r'isStreamMute',
    r'(I)Z',
  );

  static final _isStreamMute =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public boolean isStreamMute(int streamType)`
  core$_.bool isStreamMute(core$_.int streamType) {
    return _isStreamMute(
      reference.pointer,
      _id_isStreamMute.pointer,
      streamType,
    ).boolean;
  }

  static final _id_setStreamVolume = DeviceVolumeHelper._class.instanceMethodId(
    r'setStreamVolume',
    r'(III)V',
  );

  static final _setStreamVolume =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void setStreamVolume(int streamType, int index, int flags)`
  void setStreamVolume(
    core$_.int streamType,
    core$_.int index,
    core$_.int flags,
  ) {
    _setStreamVolume(
      reference.pointer,
      _id_setStreamVolume.pointer,
      streamType,
      index,
      flags,
    ).check();
  }

  static final _id_adjustStreamVolume = DeviceVolumeHelper._class
      .instanceMethodId(r'adjustStreamVolume', r'(III)V');

  static final _adjustStreamVolume =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void adjustStreamVolume(int streamType, int direction, int flags)`
  void adjustStreamVolume(
    core$_.int streamType,
    core$_.int direction,
    core$_.int flags,
  ) {
    _adjustStreamVolume(
      reference.pointer,
      _id_adjustStreamVolume.pointer,
      streamType,
      direction,
      flags,
    ).check();
  }
}

final class $DeviceVolumeHelper$Type$ extends jni$_.JType<DeviceVolumeHelper> {
  @jni$_.internal
  const $DeviceVolumeHelper$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/device_volume/DeviceVolumeHelper;';
}
